---
# tasks file for postgresql-svr
- name: Add PostgreSQL package signing key
  become: true
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  become: true
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install PostgreSQL apt package
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "postgresql-{{ postgresql.version }}"
